using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NAnt")]
[assembly: AssemblyDescriptionAttribute("A .NET Utility library")]
[assembly: AssemblyConfigurationAttribute("dev")]
[assembly: AssemblyCompanyAttribute("http://code.google.com/p/nutilities")]
[assembly: AssemblyProductAttribute("NUtilities")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2009 Rob DeCarlo")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.1.2.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1")]

